services:
  ui:
    build:
      context: ../TodoApp
      dockerfile: vps.dockerfile
    ports:
      - "80:80"
  api:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
