services:
  api:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
