name: Kotlin Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
      # - name: Setup Gradle # Looks like this is not needed
      #   uses: gradle/actions/setup-gradle@v4
      - name: Build and test with Gradle # TODO: Check why java 22 is used by gradlew
        run: ./gradlew build shadowJar --no-daemon
      - name: Copy files to VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | awk '{gsub(/\\n/,"\n")}1' > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          sftp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} -v ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            mkdir -p /home/${{ secrets.SSH_USER }}/TodoApp/build/libs
            put build/libs/TodoAPI-1.0-SNAPSHOT-all.jar /home/${{ secrets.SSH_USER }}/TodoAPI/build/libs
            put Dockerfile /home/${{ secrets.SSH_USER }}/TodoAPI/
            put docker-compose.yml /home/${{ secrets.SSH_USER }}/TodoAPI/
            EOF
